### ISSUE TITLE
install modules from url in julia_install_package

### ISSUE THREAD

**Issue by ccshao** [Non-Contradiction/JuliaCall#106]
Sometimes I need to install a modified julia module, and currently `julia_install_package` only accepts the package name. Could you kindly add a feature taking a module url as well in `julia_install_package`?

Thanks!

**Comment by Non-Contradiction** [comment]
Thanks for the feedback!
JuliaCall on the master should b able to accept things such as Github URLs.
Also, I will try to make a new release.

**Comment by ccshao** [comment]
Thanks very much for the quick update, the github version works with url.
