### ISSUE TITLE
round-trip of array with axis names comes back without names

### ISSUE THREAD

**Issue by phaverty** [Non-Contradiction/JuliaCall#11]
RCall can import an R array as a NamedArray or as an AxisArray, keeping the dimnames.

reval("x = matrix(1:6,ncol=3, dimnames=list(a=letters[1:2],b=LETTERS[1:3]))")
y rcopy(NamedArray,"x")
y = y + 20
@rput y
rcopy(AxisArray,R"y")

JuliaCall could be made to do the same trick
x = matrix(1:6,ncol=3,dimnames=list(a=letters[1:2], b=LETTERS[1:3]))
julia_command('rcopy(AxisArray,R"x")') # So far, so good, dimnames intact
julia_eval("x") # dimnames gone

Maybe I'm missing a trick here, but I think JuliaCall is dropping the dimnames.

**Comment by Non-Contradiction** [comment]
Thank you for the feedback. JuliaCall uses RObject(x) to transfer julia object into R object, which uses sexp in RCall. I will check about the difference between @rput and sexp.

**Comment by Non-Contradiction** [comment]
Actually, @rput relies on sexp as well, so the effect of @rput and sexp should be the same. Actually, this works for me:

    library(JuliaCall)
    julia_setup()
    x = matrix(1:6,ncol=3,dimnames=list(a=letters[1:2], b=LETTERS[1:3]))
    julia_library("NamedArrays")
    julia_library("AxisArrays")
    julia_command('y = rcopy(AxisArray,R"x")') # So far, so good, dimnames intact
    ##  julia_command('y = y + 20') not work for me, this should be a problem in AxisArray
    julia_eval("y")

And the result is

    > julia_eval("y")
       b
    a   A B C
      a 1 3 5
      b 2 4 6

**Comment by Non-Contradiction** [comment]
So there should be no real issue here. 

    x = matrix(1:6,ncol=3,dimnames=list(a=letters[1:2], b=LETTERS[1:3]))
    julia_command('rcopy(AxisArray,R"x")') # So far, so good, dimnames intact
    julia_eval("x") #this should cause UndefVarError: x not defined, because x is an R object

**Comment by phaverty** [comment]
Perfect, thanks. I suspected that I just misunderstood.
