### ISSUE TITLE
Install Github Pkg

### ISSUE THREAD

**Issue by JohnCoene** [Non-Contradiction/JuliaCall#111]
Thank you so much for this great package!

I was wondering if improvements to `julia_install_package` could be made so that one could install packages from Github

```julia
using Pkg

Pkg.add(PackageSpec(path="https://github.com/JuliaData/DataFrames.jl"))
```

Or

```julia
pkg> add https://github.com/JuliaData/DataFrames.jl
```

**Comment by Non-Contradiction** [comment]
Thank you for the feedback! 

Which version of JuliaCall are you using? 

From JuliaCall 0.16.6, URL should be supported in `julia_install_package`, like `julia_install_package("https://github.com/JuliaData/DataFrames.jl")`.

**Comment by JohnCoene** [comment]
Oh lord, do I feel stupid, I had tried everything but that...

Thanks again!

**Comment by Non-Contradiction** [comment]
You are welcome! I also add more documentation for the package related functions and cover the usage of installation packages from Github.
