### ISSUE TITLE
Support for custom system image?

### ISSUE THREAD

**Issue by JackDunnNZ** [Non-Contradiction/JuliaCall#125]
I'm not sure how much effort it would be, but it would be great if JuliaCall allowed you to specify the path to a system image file to use when initializing Julia (the equivalent of the `-J` flag in Julia).

In case it helps with implementation, this is supported in pyjulia via the [`sysimage` keyword](https://pyjulia.readthedocs.io/en/latest/api.html#julia.api.LibJulia.sysimage).

**Comment by Non-Contradiction** [comment]
After some initial investigation, it should be possible to support specific system image without much effort. I will try to implement it this month. Thanks for the information link to pyjulia!

**Comment by jlperla** [comment]
Any update on this feature (or pointers to where the R code could be modified for a PR)?  Also, would love see what other options there are such as choosing the num_threads/etc.

Thanks!

**Comment by dgrominski** [comment]
I might have figured out how it is to implement.  I made a PR which is working on my windows box. Couldn't test it on mac or Linux. so take it with care :-). #140

**Comment by asiripanich** [comment]
@Non-Contradiction should you close this issue since the feature has been implemented in #140 ? Just to avoid any future confusion. :)
