### ISSUE TITLE
julia_update_package("DataFrame") should be DataFrames

### ISSUE THREAD

**Issue by GantZA** [Non-Contradiction/JuliaCall#132]
<details> <summary><strong>Session Info</strong></summary>

I've run the `devtools::check()` function and found that on line 14 of package.R, the package is called `DataFrame` instead of `DataFrames`.

</details>

**Comment by GantZA** [comment]
Sorry, I've just seen that you may have intentionally said "DataFrame" instead of "DataFrames" as it is a dontrun test?

**Comment by Non-Contradiction** [comment]
Yes, it should have been `DataFrames`. The `donttest` is unrelated. Will soon submit a correction for this!
Thank you for catching this!
