### ISSUE TITLE
Trouble passing dims argument to argmax via julia_call

### ISSUE THREAD

**Issue by jpkrooney** [Non-Contradiction/JuliaCall#162]
Hi. I'm trying to call Julia's`argmax` function across slices of a 3d array - that is I want to call `argmax`  on a 3d array with `dims = (1,2)` - but I'm getting an error relating to passing in the dimensions  A reprex:

```
library(JuliaCall)

n = 5 ; d = 10 ; nx = 400 ; v = 15
array3d <- array( runif(n*v*d ,-1,0),
                  dim = c(n, v, d) )

julia_call( "argmax", array3d, dims="(1,2)" )
```

This produces the result:
<img width="923" alt="Screenshot 2021-03-08 at 12 03 02" src="https://user-images.githubusercontent.com/41968663/110313819-47a42c00-8007-11eb-9ee5-710f737d68e4.png">

I'm not sure am I doing something wrong or is it a bug ?
In Julia itself this works:
```julia
A = zeros(2,2,2)
A[:,:,1] = [1 2; 3 4]
A[:,:,2] = [10 20; 30 40]
argmax(A, dims=(1, 2))
```

<details> <summary><strong>Session Info</strong></summary>

```r
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_IE.UTF-8/en_IE.UTF-8/en_IE.UTF-8/C/en_IE.UTF-8/en_IE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] JuliaCall_0.17.2

loaded via a namespace (and not attached):
 [1] compiler_4.0.3 magrittr_2.0.1 plyr_1.8.6     tools_4.0.3    reshape2_1.4.4 yaml_2.2.1     Rcpp_1.0.6    
 [8] stringi_1.5.3  knitr_1.31     xfun_0.20      stringr_1.4.0 

```
</details>

**Comment by Non-Contradiction** [comment]
Hi, thank you very much for the feedback!

Every argument to the `julia_call` except the  julia function name should be some R object, which will be converted to some corresponding Julia object in the execution of the `julia_call`.
In your example, string `"(1, 2")` in R will be converted to string `"(1, 2)"` in julia, which is not the Tuple `(1, 2)` in julia as you expected. 

The correct way is `julia_call( "argmax", array3d, dims=julia_eval("(1,2)") )`. So `JuliaCall` knows that `"(1,2)"` needs to be interpreted as some julia code instead of some R string.

**Comment by jpkrooney** [comment]
Ahhh I see - that makes sense. Sorry I couldn't find examples of this in practice. Now that it runs, it returns a JuliaObject Cartesian Index - how can I convert this to an r matrix/dataframe ?

**Comment by Non-Contradiction** [comment]
I'm not sure what format of matrix/dataframe you want. But you can access the element in the JuliaObject by something like
```
index = julia_call( "argmax", array3d, dims="(1,2)" )
index[1][1]; index[1][2]; index[1][3];
```
and then you can collect the elements in R as you want.  I'm not very familiar with this Cartesian Index, so maybe there is some shortcut function I don't know. The best source is to see how to use Cartesian Index in julia. The JuliaObject should support most of the julia functions working on Cartesian Index with `julia_call`. For example, you can use
```
julia_call("getindex", array3d, index)
```
to directly retrieve element using the index in the form of JuliaObject.

**Comment by jpkrooney** [comment]
Ahh ok 👍
Thanks very much for your help - looks like a great package. I'll close this issue off now!
