### ISSUE TITLE
`install_julia()` does not install latest version of Julia (1.7.0 or higher) but 1.5

### ISSUE THREAD

**Issue by s3alfisc** [Non-Contradiction/JuliaCall#183]
`install_julia()` does not install the latest version of Julia (1.7.0 or higher) but 1.5. Is this behavior desired?

The 'error' occurs in the `latest_julia_version()` function, where Julia is downloaded based on the following URL: "https://raw.githubusercontent.com/JuliaBinaryWrappers/Julia_jll.jl/master/Project.toml".

```
library(JuliaCall)
install_julia()
#trying URL 'https://raw.githubusercontent.com/JuliaBinaryWrappers/Julia_jll.jl/master/Project.toml'
#Content type 'text/plain; charset=utf-8' length 259 bytes
#downloaded 259 bytes

#trying URL 'https://github.com/JuliaBinaryWrappers/Julia_jll.jl/releases/download/Julia-v1.5.0+0/Julia.v1.5.0.x86_64-w64-mingw32-libgfortran4-cxx11.tar.gz'
#Content type 'application/octet-stream' length 120914575 bytes (115.3 MB)
#downloaded 115.3 MB

```

**Comment by s3alfisc** [comment]
Hi @jpkrooney, unfortunately I haven't! I still believe that only the URL above needed to be changed.

**Comment by JackDunnNZ** [comment]
As per https://github.com/JuliaPackaging/Yggdrasil/pull/2315, Julia_jll is unmaintained and hasn't been updated in a long time. A while back I updated the code to pull from the official releases instead, I will open a PR

**Comment by s3alfisc** [comment]
Wow, this looks great, @JackDunnNZ! Thanks so much!
