### ISSUE TITLE
GPL license

### ISSUE THREAD

**Issue by randy3k** [Non-Contradiction/JuliaCall#27]
As we are using Rcpp, we may need to switch to GPL license as most R packages do.

**Comment by Non-Contradiction** [comment]
I'm not sure. `reticulate` uses Apache License.

**Comment by randy3k** [comment]
Obviously, I am not a lawyer. But from what I understand from reading https://www.apache.org/licenses/GPL-compatibility.html
reticulate should not use Apache 2.0. It is not in any sense compatible with GPL V2.

**Comment by randy3k** [comment]
Oh, May be it’s the reason? Rcpp is released as GPL v2 or later and Apache 2.0 only is incompatible with GPL v3 in this manner

> This licensing incompatibility applies only when some Apache project software becomes a derivative work of some GPLv3 software, because then the Apache software would have to be distributed under GPLv3. This would be incompatible with ASF's requirement that all Apache software must be distributed under the Apache License 2.0.

**Comment by Non-Contradiction** [comment]
Here <https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses> says MIT is compatible with GPL. So I think the source code for the JuliaCall package could still be distributed under MIT?

**Comment by randy3k** [comment]
That only means we could mix any MIT code into a GPL software, nit the vice versa.

**Comment by randy3k** [comment]
I guess Apache 2.0 is also an alternative if you don’t like being copyleft. As far as I understand, Apache 2.0 works because JuliaCall is not “Apache Software”?

**Comment by randy3k** [comment]
I believe the correct license should be GPL: http://dirk.eddelbuettel.com/code/rcpp/Rcpp-FAQ.pdf
It has to be GPL whenever we link against `libR`.

> The Rcpp package is licensed under the terms of the GNU GPL 2 or later, just like R itself. A key goal of the Rcpp package is to make extending R more seamless. But by linking your code against R (as well as Rcpp), the combination is bound by the GPL as well. This is very clearly stated at the [FSF website](https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic):

>> Linking a GPL covered work statically or dynamically with other modules is making a combined work based on the GPL covered work. Thus, the terms and conditions of the GNU General Public License cover the whole combination.

> So you are free to license your work under whichever terms you find suitable (provided they are GPL-compatible, see the FSF site for details). However, the combined work will remain under the terms and conditions of the GNU General Public License. This restriction comes from both R which is GPL-licensed as well as from Rcpp and whichever other GPL-licensed components you may be linking against.

By this reasoning, `reticulate`, `dplyr` and `tidyr` are actually wrongly licensed.

However, in practice, no one cares.......

**Comment by randy3k** [comment]
https://softwareengineering.stackexchange.com/questions/254737/does-an-rcpp-dependent-package-require-a-gpl-license

Dirk Eddelbuettel clarified that we could license JuliaCall using MIT license, but the aggregate (I guess it refers to the binary) would be licensed under GPL.

**Comment by randy3k** [comment]
Sorry for bringing in the noise. I originally thought that R and Rcpp are GPL licensed so any packages use them should be GPL'ed. It was a confusion between an R package and the corresponding `aggregate`.

**Comment by Non-Contradiction** [comment]
No need to feel sorry. The question is confusing itself. As I understand, the source files in the package could be licensed under MIT as long as we don't copy/paste or modify codes from GPL softwares. If we want to incorporate codes, for example, from RJulia, which is licensed under GPL, the problem here will happen.

**Comment by randy3k** [comment]
> the source files in the package could be licensed under MIT

JuliaCall links to R/Rcpp, with the linking, the combination (aggregate) should be issued at GPL. The concept of aggregate was not clear to me. I assume that it is the binary `JuliaCall.so` which includes R/Rcpp code.
