### ISSUE TITLE
Segmentation fault on Ubuntu 16.04 (64-bit), Julia 0.6.1

### ISSUE THREAD

**Issue by vh-d** [Non-Contradiction/JuliaCall#29]
## The issue

Running `julia_setup()` with both CRAN and master version of JuliaCall yields something like this:
 
    > julia_setup()
    Julia version 0.6.1 at location /opt/julia/bin will be used.
    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7fe5aef1de4f)
    Allocations: 815461 (Pool: 814408; Big: 1053); GC: 0
    Segmentation fault (core dumped)
    Julia initiation...
    Error in juliacall_initialize(.julia$dll_file) : 
    Expecting a single string value: [type=character; extent=0].
    In addition: Warning message:
    running command ''/opt/julia/bin/julia' '-e' 'print(Libdl.dlpath("libjulia"))'' had status 139 

## Logs by  `devtools::check()`

00install.out:

    * using log directory ‘/tmp/RtmpThQ8H9/JuliaCall.Rcheck’
    * using R version 3.4.3 (2017-11-30)
    * using platform: x86_64-pc-linux-gnu (64-bit)
    * using session charset: UTF-8
    * using options ‘--no-manual --as-cran’
    * checking for file ‘JuliaCall/DESCRIPTION’ ... OK
    * checking extension type ... Package
    * this is package ‘JuliaCall’ version ‘0.12.0.9000’
    * package encoding: UTF-8
    * checking package namespace information ... OK
    * checking package dependencies ... OK
    * checking if this is a source package ... OK
    * checking if there is a namespace ... OK
    * checking for executable files ... OK
    * checking for hidden files and directories ... OK
    * checking for portable file names ... OK
    * checking for sufficient/correct file permissions ... OK
    * checking whether package ‘JuliaCall’ can be installed ... OK
    * checking installed package size ... OK
    * checking package directory ... OK
    * checking ‘build’ directory ... OK
    * checking DESCRIPTION meta-information ... OK
    * checking top-level files ... OK
    * checking for left-over files ... OK
    * checking index information ... OK
    * checking package subdirectories ... OK
    * checking R files for non-ASCII characters ... OK
    * checking R files for syntax errors ... OK
    * checking whether the package can be loaded ... OK
    * checking whether the package can be loaded with stated dependencies ... OK
    * checking whether the package can be unloaded cleanly ... OK
    * checking whether the namespace can be loaded with stated dependencies ... OK
    * checking whether the namespace can be unloaded cleanly ... OK
    * checking loading without being on the library search path ... OK
    * checking dependencies in R code ... OK
    * checking S3 generic/method consistency ... OK
    * checking replacement functions ... OK
    * checking foreign function calls ... OK
    * checking R code for possible problems ... OK
    * checking Rd files ... OK
    * checking Rd metadata ... OK
    * checking Rd line widths ... OK
    * checking Rd cross-references ... OK
    * checking for missing documentation entries ... OK
    * checking for code/documentation mismatches ... OK
    * checking Rd \usage sections ... OK
    * checking Rd contents ... OK
    * checking for unstated dependencies in examples ... OK
    * checking line endings in C/C++/Fortran sources/headers ... OK
    * checking compiled code ... OK
    * checking installed files from ‘inst/doc’ ... OK
    * checking files in ‘vignettes’ ... OK
    * checking examples ... OK
    * checking for unstated dependencies in ‘tests’ ... OK
    * checking tests ... ERROR
    Running ‘testthat.R’
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
    testthat results ================================================================
    OK: 12 SKIPPED: 0 FAILED: 12
    1. Error: test of the JuliaObject (@test_JuliaObject.R#5) 
    2. Error: test of JuliaTuple (@test_JuliaTuple.R#5) 
    3. Error: test of using RCall through JuliaCall (@test_RCall.R#5) 
    4. Error: test of the asR functions (@test_asR.R#5) 
    5. Error: test of the basic functionality (@test_basic.R#5) 
    6. Error: test of basic generics (@test_dispatch.R#32) 
    7. Error: test of Compare group (@test_dispatch.R#51) 
    8. Error: test of Arith group (@test_dispatch.R#63) 
    9. Error: test of Logic group (@test_dispatch.R#76) 
    1. ...
    
    Error: testthat unit tests failed
    Execution halted
    * checking for unstated dependencies in vignettes ... OK
    * checking package vignettes in ‘inst/doc’ ... OK
    * checking re-building of vignette outputs ... OK
    * DONE
    Status: 1 ERROR

testthat.Rout.fail:

    R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
    Copyright (C) 2017 The R Foundation for Statistical Computing
    Platform: x86_64-pc-linux-gnu (64-bit)

    R is free software and comes with ABSOLUTELY NO WARRANTY.
    You are welcome to redistribute it under certain conditions.
    Type 'license()' or 'licence()' for distribution details.

    R is a collaborative project with many contributors.
    Type 'contributors()' for more information and
    'citation()' on how to cite R or R packages in publications.

    Type 'demo()' for some demos, 'help()' for on-line help, or
    'help.start()' for an HTML browser interface to help.
    Type 'q()' to quit R.

    > library(testthat)
    > library(JuliaCall)
    > test_check("JuliaCall")
    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7f285acfde4f)
    Allocations: 815450 (Pool: 814396; Big: 1054); GC: 0
    Segmentation fault (core dumped)
    [31m1. Error: test of the JuliaObject (@test_JuliaObject.R#5) [39m----------------------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_JuliaObject.R:5
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7f4537c08e4f)
    Allocations: 815449 (Pool: 814396; Big: 1053); GC: 0
    Segmentation fault (core dumped)
    [31m2. Error: test of JuliaTuple (@test_JuliaTuple.R#5) [39m----------------------------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_JuliaTuple.R:5
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7f7a4325fe4f)
    Allocations: 815450 (Pool: 814396; Big: 1054); GC: 0
    Segmentation fault (core dumped)
    [31m3. Error: test of using RCall through JuliaCall (@test_RCall.R#5) [39m--------------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_RCall.R:5
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7f0d10344e4f)
    Allocations: 815449 (Pool: 814396; Big: 1053); GC: 0
    Segmentation fault (core dumped)
    [31m4. Error: test of the asR functions (@test_asR.R#5) [39m----------------------------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_asR.R:5
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7f5fa38d5e4f)
    Allocations: 815450 (Pool: 814396; Big: 1054); GC: 0
    Segmentation fault (core dumped)
    [31m5. Error: test of the basic functionality (@test_basic.R#5) [39m--------------------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_basic.R:5
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7f6333040e4f)
    Allocations: 815449 (Pool: 814396; Big: 1053); GC: 0
    Segmentation fault (core dumped)
    [31m6. Error: test of basic generics (@test_dispatch.R#32) [39m-------------------------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_dispatch.R:32
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7fb4088bfe4f)
    Allocations: 815451 (Pool: 814396; Big: 1055); GC: 0
    Segmentation fault (core dumped)
    [31m7. Error: test of Compare group (@test_dispatch.R#51) [39m--------------------------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_dispatch.R:51
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7fbe4bf1ee4f)
    Allocations: 815449 (Pool: 814396; Big: 1053); GC: 0
    Segmentation fault (core dumped)
    [31m8. Error: test of Arith group (@test_dispatch.R#63) [39m----------------------------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_dispatch.R:63
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7eff6a13ce4f)
    Allocations: 815451 (Pool: 814396; Big: 1055); GC: 0
    Segmentation fault (core dumped)
    [31m9. Error: test of Logic group (@test_dispatch.R#76) [39m----------------------------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_dispatch.R:76
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7f1054cc9e4f)
    Allocations: 815449 (Pool: 814396; Big: 1053); GC: 0
    Segmentation fault (core dumped)
    [31m10. Error: test of Math and Math2 group (@test_dispatch.R#84) [39m------------------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_dispatch.R:84
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7f9acc406e4f)
    Allocations: 815450 (Pool: 814396; Big: 1054); GC: 0
    Segmentation fault (core dumped)
    [31m11. Error: test of the error handling functionality (@test_error.R#5) [39m----------
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_error.R:5
    2: juliacall_initialize(.julia$dll_file)

    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7f688f504e4f)
    Allocations: 815449 (Pool: 814396; Big: 1053); GC: 0
    Segmentation fault (core dumped)
    [31m12. Error: test of functionality related to julia_package (@test_julia_package.R#5) [39m
    Expecting a single string value: [type=character; extent=0].
    1: julia_setup() at testthat/test_julia_package.R:5
    2: juliacall_initialize(.julia$dll_file)

    testthat results ================================================================
    OK: 12 SKIPPED: 0 FAILED: 12
    1. Error: test of the JuliaObject (@test_JuliaObject.R#5) 
    2. Error: test of JuliaTuple (@test_JuliaTuple.R#5) 
    3. Error: test of using RCall through JuliaCall (@test_RCall.R#5) 
    4. Error: test of the asR functions (@test_asR.R#5) 
    5. Error: test of the basic functionality (@test_basic.R#5) 
    6. Error: test of basic generics (@test_dispatch.R#32) 
    7. Error: test of Compare group (@test_dispatch.R#51) 
    8. Error: test of Arith group (@test_dispatch.R#63) 
    9. Error: test of Logic group (@test_dispatch.R#76) 
    1. ...

    Error: testthat unit tests failed
    Execution halted

**Comment by Non-Contradiction** [comment]
Thank you very much for the feedback!
The problem seems to be related to that JuliaCall can't locate the libjulia correctly.
Could you try to open julia and see what is the result of `Libdl.dlpath("libjulia")`?

**Comment by vh-d** [comment]
You are right!

    julia> Libdl.dlpath("libjulia")
    Two passes with the same argument (-LowerSIMDLoop) attempted to be registered!

    signal (11): Segmentation fault
    while loading no file, in expression starting on line 0
    unknown function (ip: 0x7f3482fc1e4f)
    Allocations: 1007153 (Pool: 1006016; Big: 1137); GC: 0
    Segmentation fault (core dumped)

Looks more like a julia (or at least my installation) issue.

I will try to look for help in julia community. Thanks for the prompt response!

**Comment by vh-d** [comment]
https://github.com/Non-Contradiction/JuliaCall/commit/cac9f39c477d28584451d3b7f4d606804c7887b0 actually solves this issue for me

thanks!

**Comment by Non-Contradiction** [comment]
Great! 
I can't check the fix myself. Thank you for the feedback!
