### ISSUE TITLE
R.app GUI cannot find julia?

### ISSUE THREAD

**Issue by Non-Contradiction** [Non-Contradiction/JuliaCall#3]
On mac in R.app GUI, when I try to use JuliaCall, I encounter a problem: 
/bin/sh: julia: command not found 
even julia is on the path. Can't reproduce this error in terminal or RStudio.

> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/zh_CN.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1

**Comment by Non-Contradiction** [comment]
Not sure what is the reason for this. But next thing is to be able to set julia path. It seems to be ok with system("path_to_julia/julia ...") and not ok with system("julia ...")

**Comment by randy3k** [comment]
It is because in macOS, the environment variable `PATH` is set by launchctl not the SHELL.

You can need to do `bash -l -c "which julia'` to determine the path to julia.
