### ISSUE TITLE
Add juliarc.jl at julia startup

### ISSUE THREAD

**Issue by dgrominski** [Non-Contradiction/JuliaCall#30]
Adding juliarc.jl at start up  helps if e.g. a custom path for the package folder is defined there.

I run into the issue trying to use Julia Call with juliapro 6.2 on Windows Server 2012, where the package folder is JULIA_HOME/.pkgs--.6.2.1.  Including  juliarc.j into the JuliaCall's setup.jl made the package folder visible. Though I'm not shure if it is the best solution.

And thank you for a great package. It has a true potential to replace Rcpp, at least for me.

Best
Dmitri

**Comment by Non-Contradiction** [comment]
Thank you for the feedback. I'm glad that the package is helpful!
I looked into julia and found there is a `Base.load_juliarc` function both in julia 0.6 and current master. I will submit a commit to call that function  at `julia_setup`soon and you can see if that works for you.

**Comment by dgrominski** [comment]
Just tried the patch, but it seems not to fix the issue. It seems Julia tries to find packages prior to call of Base.load_juliarc. 
```
Julia version 0.6.2 at location E:\luliapro\julia-0.6.2\bin will be used.
Julia initiation...
Finish Julia initiation.
Loading setup script for JuliaCall...
LoadError("E:\\R-Portable\\App\\R-Portable\\library\\JuliaCall\\julia\\setup.jl", 9, ArgumentError("Module Suppressor not found in current path.\nRun `Pkg.add(\"Suppressor\")` to install the Suppressor package.")) 
 Show Traceback
 
 Rerun with Debug
 Error in .julia$cmd(paste0("include(\"", system.file("julia/setup.jl",  : 
  Error happens when you try to execute command include("E:/R-Portable/App/R-Portable/library/JuliaCall/julia/setup.jl") in Julia. 
``````

Moving the line     `julia_call("Base.load_juliarc")` higher to just prior to `install_dependency()`  does not help either as it results in an endless loop of printing 

```
Julia version 0.6.2 at location E:\luliapro\julia-0.6.2\bin will be used.
Julia initiation...
Finish Julia initiation.
Loading setup script for JuliaCall... 
```
Lastly adding the Base.load_juliarc directly to setup.jl at the first line lead to success:
```
Base.load_juliarc()
module JuliaCall

# gc_enable(false)
```

**Comment by Non-Contradiction** [comment]
Yes, you are right. In the previous patch it is too late to load the juliarc (it is equivalent to add the line at the last of setup.jl). The first line at the setup.jl is the right place to go and it will be the first thing evaluated in the embedded julia. 
Pull request is welcomed. I can also submit a patch later after several hours.
Thank you very much!

**Comment by dgrominski** [comment]
#31 Just made the PR,
