### ISSUE TITLE
Pushing an R formula to Julia

### ISSUE THREAD

**Issue by dmbates** [Non-Contradiction/JuliaCall#37]
I was planning on submitting a PR but I haven't been able to work out where this happens.

@randy3k has added a capability to the development version of [`RCall`](https://github.com/JuliaInterop/RCall.jl) to convert an R formula to a Julia formula with `rcopy`.
```julia
julia> using RCall

julia> rcopy(R"y ~ 1 + service + (1|s) + (1|d) + (1|dept)")
Formula: y ~ 1 + service + (1 | s) + (1 | d) + (1 | dept)
```

I haven't been able to work out how to hook into this rcopy conversion to "push" an R formula to Julia through `JuliaCall`.  If, for example, I use `julia_assign` with the second argument being an R formula it ends up in Julia as a `Ptr{LangSxp}` rather than running through the `rcopy` conversion.

From my point of view, using `rcopy` can "pull" an R formula to Julia but I don't know how to "push" one through `JuliaCall`.

**Comment by Non-Contradiction** [comment]
Instead of applying `rcopy` one by one, `JuliaCall` applies `rcopy` on a list which containing everything that needs to be converted. Here is the type conversion code in `JuliaCall` `setup.jl`:
```
function transfer_list(x)
    rcopy(RObject(Ptr{RCall.VecSxp}(x)))
end
```
The argument `x` is the list that needs to be converted. And here is something that I found:
```
transfer_list(rcall(:list, R"y ~ x + (1 | g)").p)
# Any[1]
# RCall.RObject{RCall.LangSxp}

transfer_list(rcall(:list, R"1", R"1L").p)
# Any[2]
# 1.00
# 1
```
The list that contains formula isn't converted as expected. I need to check what causes this.

**Comment by randy3k** [comment]
https://github.com/JuliaInterop/RCall.jl/commit/8b712557b29b6ba8965e522307ad5f84ac2c7ca7 should fix it.

**Comment by randy3k** [comment]
Oh, there is a bug, will push a fix soon.

**Comment by Non-Contradiction** [comment]
It works now using the RCall master, for example,
```
> julia_call("typeof", y ~ 1 + service + (1|s) + (1|d) + (1|dept))
Julia Object of type DataType.
StatsModels.Formula
> 
```

**Comment by randy3k** [comment]
v0.10.3 has just been released.
