### ISSUE TITLE
Capturing Julia output

### ISSUE THREAD

**Issue by dmbates** [Non-Contradiction/JuliaCall#43]
I am having difficulty deciding how to capture Julia output from a Julia `print` or similar call in an Rmd document.  See http://rpubs.com/dmbates/377897 where I try to print
```{r jprint}
j$eval("print(fm1)")
```
(just before the section on "Fitting the model in Julia using RCall").  The output from that chunk appears in the RStudio R Markdown console, not in the document.

Also, if there are parts of my explanation of how to use JuliaCall that you would like changed, please let me know.

**Comment by Non-Contradiction** [comment]
The julia `print` command will send things to julia stdout and currently the julia stdout is not captured by `JuliaCall`.

But things like `j$eval("fm1")` should give a wrapper for `fm1` in R, and it will trigger the corresponding display method, which is overloaded by `JuliaCall`,  which should be okay both from the console and rmd document,
for example, on my RStudio console, it gives the following result (and I will also check about rmd document soon):
```
> j <- julia_setup()
> j$library("MixedModels")
INFO: Precompiling module MixedModels.
> library(lme4)
> attach("~/.julia/v0.6/MixedModels/test/dat.rda")
The following objects are masked from package:lme4:

    Arabidopsis, cake, cbpp, Dyestuff, Dyestuff2, grouseticks, InstEval,
    Pastes, Penicillin, sleepstudy, VerbAgg

> str(kb07)
'data.frame':	1790 obs. of  10 variables:
 $ G: Factor w/ 56 levels "30","31","34",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ H: Factor w/ 32 levels "1","2","3","4",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ Y: num  2267 3856 1567 1732 2660 ...
 $ S: num  1 -1 -1 1 1 -1 -1 1 1 -1 ...
 $ T: num  -1 1 -1 1 -1 1 -1 1 -1 1 ...
 $ U: num  1 -1 -1 -1 -1 1 1 1 1 -1 ...
 $ V: num  -1 -1 1 1 -1 -1 1 1 -1 -1 ...
 $ W: num  1 1 1 -1 -1 -1 -1 1 1 1 ...
 $ X: num  -1 -1 1 -1 1 1 -1 1 -1 -1 ...
 $ Z: num  -1 1 -1 -1 1 -1 1 1 -1 1 ...
> fm1 <- j$call("fit", j$eval("LinearMixedModel"), Y ~ 1+S+T+U+V+W+X+Z + (1+S+T+U+V+W+X+Z|G) + (1+S+T+U+V+W+X+Z|H), kb07)
> fm1
Julia Object of type MixedModels.LinearMixedModel{Float64}.
Linear mixed model fit by maximum likelihood
 Formula: Y ~ 1 + S + T + U + V + W + X + Z + ((1 + S + T + U + V + W + X + Z) | G) + ((1 + S + T + U + V + W + X + Z) | H)
     logLik        -2 logLik          AIC             BIC       
 -1.42931591×10⁴  2.85863181×10⁴  2.87483181×10⁴  2.91930058×10⁴

Variance components:
              Column     Variance   Std.Dev.    Corr.
 G        (Intercept)   90678.3925 301.128531
          S              5180.5766  71.976223 -0.43
          T              5538.3873  74.420342 -0.47  0.08
          U              7587.6112  87.106895  0.21 -0.20  0.41
          V              8834.9690  93.994516  0.20 -0.76 -0.54 -0.20
          W              1821.8560  42.683205  0.47 -0.53 -0.11 -0.44  0.29
          X              7425.1050  86.169049 -0.10  0.13 -0.05 -0.86 -0.06  0.70
          Z              3805.3075  61.687174 -0.48  0.41 -0.39 -0.09  0.18 -0.78 -0.39
 H        (Intercept)  129927.0794 360.453991
          S              1854.1518  43.059863 -0.34
          T             62424.3596 249.848673 -0.68 -0.45
          U              2949.0760  54.305396  0.20 -0.03 -0.18
          V              1040.2093  32.252276  0.57 -0.76  0.02  0.01
          W              1621.4556  40.267302  0.28 -0.03 -0.27  0.44 -0.21
          X              4704.0996  68.586439  0.08 -0.24  0.21 -0.13 -0.26  0.01
          Z              4831.3038  69.507581  0.04 -0.47  0.32 -0.68  0.65 -0.68 -0.10
 Residual              399611.0928 632.147999
 Number of obs: 1790; levels of grouping factors: 56, 32

  Fixed-effects parameters:
             Estimate Std.Error  z value P(>|z|)
(Intercept)   2180.63   76.8294  28.3827  <1e-99
S            -66.9899   19.3321 -3.46521  0.0005
T            -333.881   47.6754 -7.00323  <1e-11
U             78.9869   21.2351  3.71964  0.0002
V             22.1517    20.336  1.08929  0.2760
W            -18.9244   17.5066 -1.08099  0.2797
X             5.26198   22.4248  0.23465  0.8145
Z             -23.951   21.0288 -1.13896  0.2547
> 
```

**Comment by dmbates** [comment]
That didn't seem to work.  I updated the rpubs.com version.

**Comment by Non-Contradiction** [comment]
I think the issue should be fixed with the latest commit, and the former example should work, also see: <http://rpubs.com/Consistency/378365>.

**Comment by Non-Contradiction** [comment]
If not installed, `RCall.jl` will be installed automatically by `JuliaCall`, and it is possible to install and upgrade packages from `JuliaCall` as well but it may not be as stable as doing that from julia REPL. On my mac and my ubuntu VM, this works well, but on red hat in the cluster from my university, it keeps giving me some git error... 

By the way, are you interested in creating an R wrapper package for `MixedModels.jl` by the use of `JuliaCall`? The result seems promising and worths a try.

**Comment by dmbates** [comment]
@Non-Contradiction Thanks for the fix

Yes, I would be interested in creating an R wrapper package.  I think I would first like to get some feedback on what people would want from such a package - assuming people do try to use MixedModels from R.

I will be traveling next week and preparing materials this week so it will be two weeks before I start this.
