### ISSUE TITLE
Sending Functions

### ISSUE THREAD

**Issue by ChrisRackauckas** [Non-Contradiction/JuliaCall#45]
How exactly does sending a function work. If you've defined a function in R, can you just send it like any other variable? Will the get JIT compiled and specialized just like any other Julia function?

**Comment by Non-Contradiction** [comment]
In R, you typically can't `mutate` the function arguments.
The typical way to "mutate" the input is to define functions like `xxx<-` and it is not really mutating the input in the julia sense, but just creating another object and binding the new object to the old name.
The real way to mutate the input is to use the C interface of R.

`JuliaCall` doesn't modify R arguments either as the normal R function currently, but it can modify `JuliaObject`, which is just a wrapper of julia object in R. For example,

```
> a <- matrix(1,3,3)
> f <- function(a){a[1,1] = 2}
> f(a)
> a
     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1    1    1
[3,]    1    1    1
> aa <- JuliaObject(a)
> aa
Julia Object of type Array{Float64,2}.
[1.0 1.0 1.0; 1.0 1.0 1.0; 1.0 1.0 1.0]
> ff <- julia_eval("function f(a) a[1,1] = 2 end")
> ff(aa)
[1] 2
> aa
Julia Object of type Array{Float64,2}.
[2.0 1.0 1.0; 1.0 1.0 1.0; 1.0 1.0 1.0]
> 
```

Does this satisfy your need?
