### ISSUE TITLE
Installation error on Windows 10

### ISSUE THREAD

**Issue by ChrisRackauckas** [Non-Contradiction/JuliaCall#46]
Steps:

```R
install.packages("JuliaCall")
library(JuliaCall)
julia <- julia_setup()

Error in julia_setup() : Julia is not found.
```

Julia was installed using the standard generic binary.

**Comment by Non-Contradiction** [comment]
Is Julia in the path?

Maybe we could try: `julia_setup(JULIA_HOME = "the folder that contains julia binary")`

**Comment by ChrisRackauckas** [comment]
I see. Adding it to the path worked. For Windows you cannot assume that a standard installation will be added to the path though (and it's not recommended). You may just want to have it default to searching in AppData/Local for julia-... folders.

**Comment by Non-Contradiction** [comment]
Thanks for the suggestion! I will write this in Readme and write a page about common questions in setting all the things up.

**Comment by Non-Contradiction** [comment]
Information on JULIA_HOME added in the documentation.
