### ISSUE TITLE
Check libR when `julia_setup()`?

### ISSUE THREAD

**Issue by Non-Contradiction** [Non-Contradiction/JuliaCall#48]
During the `julia_setup()`, although it checks whether the `Rhome` is the current R, it doesn't check whether libR is valid, so we have problems like #44, which is caused by libR not available. I plan to add libR check during `julia_setup()` and if libR is not there or too old, gives error message about libR. Given the `validate_libR` function in `RCall.jl`, it should be really easy to do so. 

And I'm wondering whether the check should be incorporated into `RCall.jl`. If the Rhome is set, but libR is not available or too old, `RCall.jl` will install R through Conda currently without any information about the libR problem. But if the user sets the Rhome variable, it seems that the user wants to use the R at that location, would it make more sense to throw an error in this case instead of installing R through Conda? @randy3k  What do you think?

**Comment by randy3k** [comment]
I agree with you, i.e., we shouldn't install R via conda if `Rhome` is set. 


Back to the `validate_libR` issue, I believe that it is checked when RCall is loaded; isn't it sufficient?

**Comment by randy3k** [comment]
The soon-will-be-released version of RCall won't install R via conda if Rhome is set.
https://github.com/JuliaInterop/RCall.jl/releases/tag/untagged-98b309fc6c31f22579e0
