### ISSUE TITLE
Don't capture output when Julia not embedded.

### ISSUE THREAD

**Issue by Non-Contradiction** [Non-Contradiction/JuliaCall#54]
If you use `RCall` in julia and load library `JuliaCall`, `JuliaCall` will capture the Julia output. And the julia display system will be in a mess.

**Comment by randy3k** [comment]
I argue that you should not capture STDOUT. Instead, you should make a `print.JuliaObject` function.

In my earlier attempt of [juliaapi](https://github.com/juliaverse/juliaapi). Bascially `print.jl_value` [triggers](https://github.com/juliaverse/juliaapi/blob/32ceeafc58b15dafc662b0445dce3f1a41022f70/src/eval.c#L17) `sprint` in Julia and print the string to the R IO.

```
r$> library(juliaapi)

r$> juliaapi::jl_init()

r$> juliaapi::jl_eval_string("1")
1
```

Note that the output is not print the STDOUT, but the R IO (of course, in this case, the R output IO is STDOUT, but it is not necessarily true). In this way, when `R"library(JuliaCall)"` in julia, we will be able to capture output.

**Comment by randy3k** [comment]
Speaking of detecting if Julia is initialized, you could use [this](https://github.com/Non-Contradiction/JuliaCall/blob/master/src/JuliaCall.cpp#L10). Should be easier to export an Rcpp function.

**Comment by Non-Contradiction** [comment]
`JuliaCall` doesn't capture the std_out, but it brings its own display system to deal with the issue that embedded Julia doesn't have any display system, so to make the embedded Julia behaves somewhat like a "normal" Julia.  

The `JuliaCall` default display system is a special display system which captures what Julia would display in a text terminal in a buffer and then use the "print" function in Julia to "display" it.

When used not in embedded Julia, this mechanism interferes with other things....

**Comment by randy3k** [comment]
I realized the reason you did in this way soon after I posted. But my point is still valid for text output. It is better to do `Rprintf` and`sprint` instead of  Julia`print`. It will make sure it prints to R IO instead of STDOUT.

**Comment by randy3k** [comment]
My point about `jl_main_module` turns out to be wrong. You will need to load it from the libjulia first...

**Comment by Non-Contradiction** [comment]
Thanks. I will try to do it in this way. It turns out that `print` in Julia is not a robust way.

Yes, it will always return false before loading the dll...

**Comment by Non-Contradiction** [comment]
I think one possible way is to check if `RCall`'s exported symbol exists or not.
like `isdefined(:RObject)`, but the method can "easily" be broken if not `using RCall` in `Main` in first place.

**Comment by Non-Contradiction** [comment]
A more robust solution would be checking the length of `Base.Multimedia.displays`, and pushing the display system if the length is less than 2.
