### ISSUE TITLE
Problem with setup.jl

### ISSUE THREAD

**Issue by AndradeTiago** [Non-Contradiction/JuliaCall#59]
I am unable to use the package due to an error while loading setup.jl.

When I run this script directly in Julia, it run normally, however when I try to use the JuliaCall library in R, I get the following error:
___
C:\Users\Administrador>"C:\Users\Administrador\AppData\Local\Julia-0.6.4\bin\jul
ia.exe" "C:\Program Files\R\R-3.4.3\library\JuliaCall\julia\setup.jl"
ERROR: LoadError: RCall not properly installed. Please run Pkg.build("RCall")
Stacktrace:
 [1] error(::String) at .\error.jl:21
 [2] include_from_node1(::String) at .\loading.jl:576
 [3] include(::String) at .\sysimg.jl:14
 [4] anonymous at .\<missing>:2
while loading C:\Users\Administrador\.julia\v0.6\RCall\src\RCall.jl, in expressi
on starting on line 40
ERROR: LoadError: Failed to precompile RCall to C:\Users\Administrador\.julia\li
b\v0.6\RCall.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:710
 [2] _require(::Symbol) at .\loading.jl:497
 [3] require(::Symbol) at .\loading.jl:405
 [4] include_from_node1(::String) at .\loading.jl:576
 [5] include(::String) at .\sysimg.jl:14
 [6] process_options(::Base.JLOptions) at .\client.jl:305
 [7] _start() at .\client.jl:371
while loading C:\Program Files\R\R-3.4.3\library\JuliaCall\julia\setup.jl, in ex
pression starting on line 20
___

I ran the commands  Pkg.build("RCall") and Pkg.test("RCall") in Julia and did not get an error

I am using R 3.4.3 and Julia 0.6.4

**Comment by Non-Contradiction** [comment]
Hi, thank you very much for providing feedback.

From the error message, it seems that the problem is with 
https://github.com/JuliaInterop/RCall.jl/blob/192de30bda31c3d9bc16f301e9857684b4ae88fd/src/RCall.jl#L33
which suggests that there is some problem with the `deps.jl` file. So maybe we could try the following:

```
    julia> Base.Pkg.dir("RCall", "deps", "deps.jl")
    ## the previous command should return a file name, 
    ## check whether the file exists and the content of the file. 
    ## This file should exist after a successful `Pkg.build("RCall")`
    ## The file should contain the location of Rhome and libR, 
    ## libR should be where the R library is
    ## check whether the content of Rhome matches with `R.home()` from R.

    julia> ENV["R_HOME"] = "the file folder returned from R.home() in R"
    julia> Pkg.build("RCall")
    ## what is the result of this?

    julia> Base.Pkg.dir("RCall", "deps", "deps.jl")
    ## check whether the file exists and the content of this file again.

    ## find out the location of install_depency.jl script by 
    ##  R> system.file("julia/install_dependency.jl", package = "JuliaCall")
    julia> ARGS = ["the file folder returned from R.home() in R"]
    julia> include("the location of install_dependency.jl")
    ## what is the result of this?

    julia> Base.Pkg.dir("RCall", "deps", "deps.jl")
    ## check whether the file exists and the content of this file again.

    ## After all of this, do start another julia session.
    julia> using RCall

    ## what is the message?
```

**Comment by AndradeTiago** [comment]
Thanks for the help, but I tested again and it worked. Maybe the environment variable R_HOME needed a reboot to be set, just a guess.

I'll close this issue since the problem was resolved.
