### ISSUE TITLE
Problem in `julia_source` on julia v0.7+: UndefVarError: include not defined

### ISSUE THREAD

**Issue by Non-Contradiction** [Non-Contradiction/JuliaCall#65]
Following will happen when using `julia_source` in `Julia` version newer than 0.7.
```
julia_source("test.jl")
Error: Error happens in Julia.
UndefVarError: include not defined
Stacktrace:
[1] funcfind(::String) at /usr/local/lib/R/3.5/site-library/JuliaCall/julia/setup.jl:102
[2] docall(::Ptr{Nothing}) at /usr/local/lib/R/3.5/site-library/JuliaCall/julia/setup.jl:156
```

It's caused by the change in `include` function in `Julia`.

**Comment by sjmgarnier** [comment]
Thanks. I can now source a .jl file, however it will fail with the same error if the file contains an include command.

**Comment by Non-Contradiction** [comment]
Yes, the usage of `include` in `Julia` is changed.
Now you need to either use it in a module (and the source file will be "included" in the module),
or you have to use `Base.include(Module, fname)` to "include" the source file in a certain module.

So if you are using REPL and deal directly with `Main` module (which can be thought as a global scope), instead of just `include(fname)`, you now need to do `Base.include(Main, fname)`.

**Comment by sjmgarnier** [comment]
Thanks, I'll try that.

**Comment by Non-Contradiction** [comment]
Using julia v0.7 can facilitate the transition from 0.6 to 1.0.

I also just noticed this difference... so the previous implementation of `julia_source` which relies on `include` doesn't work in julia v0.7 and v1.0 and is changed to the current implementation.

**Comment by sjmgarnier** [comment]
Base.include(Main, fname) works.
