### ISSUE TITLE
@everywhere include() source files

### ISSUE THREAD

**Issue by cyclesix** [Non-Contradiction/JuliaCall#73]
Firstly I would like to say that I am thankful for JuliaCall since it allows me to use Julia functions within R at my organization (it would otherwise be a harder sell to try and use Julia).

I have some code that is contained in a number of source files. I specifically need to run some of these functions in parallel and therefore used the `@everywhere` macro to distribute to all workers.

In Julia 0.6.x I made a `headers.jl` file that contained all the `@everywhere include()` statements to the various files. I would then execute `julia_source("headers.jl")` and all my code would be included.

In Julia 1.0.0 the command fails because of the `include()` statements inside the `headers.jl` file. If i run `julia_exists("include")` it returns false. 

Curiously if i run `julia_console()` and exit it again, `julia_exists("include")` is now true and I can execute my code as before.... However I could not find away to exit the console in a script and therefore this is not a solution for me.

My workaround was to compile the code as a package and use `@everywhere using pkgX`, however this could be a cumbersome step to add.

I can't simply use `julia_source()` on all the files since I need to apply an `@everywhere` in front of them.

**Comment by Non-Contradiction** [comment]
Thank you for providing feedback!
I'm not very familiar with `@everywhere` and parallel things, `julia_source` on Julia v1.0 is just `Base.include(Main, filename)`, and its behavior should be quite similar to Julia v0.6.x, does it work with `@everywhere`?

**Comment by cyclesix** [comment]
Following your reply, I have found that importing `include` from `Base.MainInclude` as follows:
`julia_command("import Base.MainInclude.include)`
allows me to execute:
`julia_command('@everywhere include("headers.jl")')`
Thanks!

*It is still curious to me that after running `julia_console()`, it appears to do the same thing.

**Comment by Non-Contradiction** [comment]
When used in terminal `julia_console()` will activate a Julia REPL. Maybe Julia REPL will import that automatically?

**Comment by cyclesix** [comment]
It could be.

**Comment by cyclesix** [comment]
julia_command("import Base.MainInclude.include)
