### ISSUE TITLE
R segfaults unless I explicity load libjulia.so

### ISSUE THREAD

**Issue by sje30** [Non-Contradiction/JuliaCall#74]
Just getting started with JuliaCall, thanks for the package.  I find that it doesn't work for me on linux by default:

```
> setwd('/home/sje30')
> require(JuliaCall)
Loading required package: JuliaCall
> j = julia_setup()
Julia version 1.0.0 at location /alt/applic/julia/julia-1.0.0/bin will be used.

 *** caught segfault ***
address 0x38, cause 'memory not mapped'

Traceback:
 1: juliacall_initialize(.julia$dll_file)
 2: julia_setup()

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

If however I explicitly load the libjulia.so then it does work:

```
> setwd('/home/sje30')
> dyn.load("/alt/applic/julia/julia-1.0.0/lib/libjulia.so")
> require(JuliaCall)
Loading required package: JuliaCall
> j = julia_setup()
Julia version 1.0.0 at location /alt/applic/julia/julia-1.0.0/bin will be used.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.

> julia_eval("sin.([pi/4, pi/2])")
[1] 0.7071068 1.0000000
```

Any ideas what I can try to help fix this so I don't need to load the .so myself?

**Comment by Non-Contradiction** [comment]
Thank you very much for the feedback.
It looks similarly with #71 .
How about export "/alt/applic/julia/julia-1.0.0/lib/julia" into R_LD_LIBRARY_PATH or LD_LIBRARY_PATH?

**Comment by sje30** [comment]
Yes, this seems to fix it thanks.

**Comment by Non-Contradiction** [comment]
I add a `dyn.load` in `julia_setup()`, so segfault like this won't happen. But export the Julia library path into R_LD_LIBRARY_PATH is still needed in os system with old libraries.
