### ISSUE TITLE
How to capture stdout from Julia?

### ISSUE THREAD

**Issue by sje30** [Non-Contradiction/JuliaCall#76]
Is there a way to capture the stdout from Julia?

e.g. if I have a chunk like the following

```{julia,test-chunk}
@time 1+1
```

then the output "2" is caught into the html file, but the output from @time is just printed to stdout and is not caught.  As well as showing the result (2), I would like the time information to be kept in the doc.

Thanks!

**Comment by sje30** [comment]
I see there is now a way:

```
open("output.txt", "w") do out
    redirect_stdout(out) do
        println("hello")
        @time(rand(1000))
    end
end
```

is this useful for ensuring that stdout from within knitr chunks can be caught? 
seems this has been asked before: https://github.com/JuliaLang/julia/pull/3044#issuecomment-21317057  cc: @yihui

**Comment by Non-Contradiction** [comment]
I have thought about this before. There is a Julia package useful for tasks like this - [Suppressor.jl](https://github.com/JuliaIO/Suppressor.jl), which is already used by JuliaCall to suppress some warnings in `julia_setup()`.
It can be used like this to capture the stdout:
```
using Suppressor
output = @capture_out begin
    println("hello")
    @time(rand(1000))
end
```
I think I'm going to add this into JuliaCall to capture Julia stdout from Knitr chunks.
Thank you for the feedback!

**Comment by sje30** [comment]
It would be wonderful to capture julia stdout into knitr docs -- can  I help test?

**Comment by Non-Contradiction** [comment]
I just push a version of JuliaCall to master to capture the Julia stdout in RMarkdown document. It seems to work on my machine. @sje30 Would you mind to test it? Thanks.

**Comment by sje30** [comment]
thanks!

Yes, it seems to work great for me, e.g. with chunks like this:

```{julia}
@time(rand(5))
println("hello world")
```

**Comment by jeremiedb** [comment]
Should it be possible to return the Julia stdout in  the R console? 
More precisely, I want a R binding to a Julia ML library and would like to print callback information during training. The Julia library currently does it through: `println("Eval metric: ", eval_metric)`

The R call is done with the following: 

```
evo_train <- function(data_train, target_train, params=set_params()) {
  model <- JuliaCall::julia_call("grow_gbtree", data_train, target_train, params, need_return = "Julia")
  return(model)
}
```

However, no callback is shown in R console during training, while it's the case within the Julia environment. Am I missing a way to capture the callback?

**Comment by Non-Contradiction** [comment]
@jeremiedb 
Thanks for the feedback.
If the Julia function print things to stdout, then it should be displayed in R stdout as well. 
For example, this is what I get in the R console on my Mac:
```
> library(JuliaCall)
> julia_setup()
Julia version 1.0.3 at location /Applications/Julia-1.0.app/Contents/Resources/julia/bin will be used.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
> julia_command('function test() println("1") end')
test (generic function with 1 method)
  
> julia_call("test")
1
NULL
> test <- function() julia_call("test")
> test()
1
NULL
> 
```
This is what I get in RStudio:
```
> library(JuliaCall)
> julia_setup()
Julia version 1.0.3 at location /Applications/Julia-1.0.app/Contents/Resources/julia/bin will be used.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
> julia_command('function test() println("1") end')
test (generic function with 1 method)
  
> julia_call("test")
NULL
1
> test <- function() julia_call("test")
> test()
1
NULL
> 
```
So at least this should be the case on Mac for R console and RStudio. 
What is the operating system and the R environment you are using?

**Comment by jeremiedb** [comment]
Thanks for prompt reply!

I'm on Windows 10, R 3.5.2 and Julia 1.1.0. 
Interestingly, I got the same result as you on the R console, but not in the RStudio. 

R console:

```
> library(JuliaCall)
Warning message:
package 'JuliaCall' was built under R version 3.5.3
> julia_setup()
Julia version 1.1.0 at location C:\Users\Jeremie\AppData\Local\JULIA-~1.0\bin will be used.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
> julia_command('function test() println("1") end')
test (generic function with 1 method)

> julia_call("test")
1
NULL
>
```

RStudio (1.1.463):

```
> julia_command('function test() println("1") end')
test (generic function with 1 method)
  
> julia_call("test")
NULL
> test <- function() julia_call("test")
> test()
NULL
```

I'll check on newest RStudio version in case something was fixed in the meatime. Any idea why the R console output would be different that from RStudio?

**Comment by jeremiedb** [comment]
Unfortunately, no luck with RStudio 1.2.1335:

```
> library(JuliaCall)
Warning message:
package ‘JuliaCall’ was built under R version 3.5.3 
> JuliaCall::julia_setup()
Julia version 1.1.0 at location C:\Users\Jeremie\AppData\Local\JULIA-~1.0\bin will be used.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
> julia_command('function test() println("1") end')
test (generic function with 1 method)
  
> julia_call("test")
NULL
> test <- function() julia_call("test")
> test()
NULL
```

But it works on Ubuntu (16.04): 

```
> library(JuliaCall)
> JuliaCall::julia_setup()
Julia version 1.1.0 at location /home/evovest/julia-1.1.0/bin will be used.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
> julia_command('function test() println("1") end')
test (generic function with 1 method)
  
> julia_call("test")
1
NULL
> test <- function() julia_call("test")
> test()
1
NULL
```

Windows... :)

**Comment by Non-Contradiction** [comment]
I guess that is because the RStudio on Windows does not capture the stdout. I am wondering what is the result of `system2("echo", "1")` (or does `echo` work on Windows?).

Capturing stdout has some small performance penalty, so I don't think it is a good idea for JuliaCall to capture this in general. And it is quite verbose to capture the Julia stdout and return it to R manually.
After some investigation, I think the most straightforward trick to make up for this is to use `display` instead of `println` in the Julia function to show the output as there is already a Julia display hook by JuliaCall. Is this easy to do in your case?

**Comment by jeremiedb** [comment]
`display` is a success! 

```
> model <- evo_train(data_train = data_train, target_train = target_train, params = params, metric = as.symbol("logloss"))
"iter:10, train:0.5405357979307208"
  
"iter:20, train:0.4820017003304175"
  
"iter:30, train:0.4579228973121646"
  
"iter:40, train:0.4467219454897902"
  
"iter:50, train:0.44318728614403574"
  
"iter:60, train:0.44304573858268476"
  
"iter:70, train:0.4429767799233615"
  
"iter:80, train:0.44279322345192285"
  
"iter:90, train:0.44279308993999805"
  ```` 

I'm unclear about what mechanism is used by display that makes it work even with Windows RStudio, but it solves the case. Thanks a lot for you help!

**Comment by Non-Contradiction** [comment]
I am happy that it works for you!

The following is a brief explanation if you are interested.

Julia provides a mechanism to redirect Julia display system globally. In `julia_setup()`, JuliaCall set up a display system which redirects every Julia display to outputs in R (which should be supported by any IDE of R) globally and then things will work continually.

However, Julia doesn't provide an easy way to redirect stdout globally, and it may not be safe to do so in an embedded application like JuliaCall under some scenarios. If we want to capture Julia stdout from JuliaCall, the easiest and most reliable way is to capture stdout locally from every JuliaCall command. However, this solution causes a performance penalty for every JuliaCall command, and it is currently only used for RMarkdown documents where displaying result may be much more important than performance.

**Comment by jeremiedb** [comment]
Thanks for taking time to provide further explanation, much appreciated!
