### ISSUE TITLE
Deprecation warning for length(df::AbstractDataFrame)

### ISSUE THREAD

**Issue by karldw** [Non-Contradiction/JuliaCall#79]
When I try to copy a dataframe to Julia with `JuliaObject`, I get a deprecation warning:
```r
library(JuliaCall)
julia_setup(install=FALSE)
mtcars_julia <- JuliaObject(mtcars)
# ┌ Warning: `length(df::AbstractDataFrame)` is deprecated, use `size(df, 2)` instead.
# │   caller = #simple_call#13(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String, ::DataFrames.DataFrame) at interface1.jl:11
# └ @ Main.JuliaCall ~/.R/current/JuliaCall/julia/interface1.jl:11
```
I think this is the place:
https://github.com/Non-Contradiction/JuliaCall/blob/master/R/dispatch.R#L2

Using Julia 1.1.0 and JuliaCall 0.16.2

**Comment by Non-Contradiction** [comment]
Thank you for the feedback.
Do you encounter the error in running `length(mtcars_julia)` or just `mtcars_julia <- JuliaObject(mtcars)`?
I have difficulty in reproducing the error by just running `mtcars_julia <- JuliaObject(mtcars)`.
Could you run `using Pkg; Pkg.update()` in Julia and try again?

**Comment by karldw** [comment]
Sorry, I realize `julia_assign` is a better way to do what I was trying to do. That function doesn't raise the deprecation warning, so I'll close this.

**Comment by sjmgarnier** [comment]
I get this warning when running `mtcars_julia <- JuliaObject(mtcars)`, but only the first time after starting Julia with `julia_setup()`. The warning is not displayed again afterwards.
