### ISSUE TITLE
RROR: UndefVarError: JULIA_HOME not defined

### ISSUE THREAD

**Issue by JasperHG90** [Non-Contradiction/JuliaCall#82]
I'm experiencing a strange issue on Ubuntu 18.04.

Julia is located at `/home/jasper/julia-1.0.3/bin/julia`. When I call 

```r
library(JuliaCall)
julia <- julia_setup()
```

After setting the JULIA_HOME variable, I get the following output:

```text
ERROR: UndefVarError: JULIA_HOME not defined
Stacktrace:
 [1] top-level scope at none:0
Error in julia_setup() : Julia is not found.
```

When I call 

```r
Sys.getenv("JULIA_HOME")
```

I see 

```text
[1] "/home/jasper/julia-1.0.3/bin//"
```

I'm unsure why Julia cannot be found. After checking your docs and trying

```r
julia <- julia_setup(JULIA_HOME = "/home/jasper/julia-1.0.3/bin/")
```

I still get

```text
ERROR: UndefVarError: JULIA_HOME not defined
Stacktrace:
 [1] top-level scope at none:0
Error in julia_setup(JULIA_HOME = "/home/jasper/julia-1.0.3/bin/") : 
  Julia is not found.
```

However, when I execute the following in a terminal

```shell
which julia
```

I see

```text
/home/jasper/julia-1.0.3/bin//julia
```

I'm not sure how to solve this. It looks like the setup should work, but somehow Julia cannot be found!

**Comment by Non-Contradiction** [comment]
Thank you for the feedback!
The ERROR: UndefVarError comes from Julia, which means there are some errors with `julia_setup` code.
I think I know the cause of the problem (Julia changes the name of JULIA_HOME in v0.6 to Sys.BINDIR in v1.0), but I think the problem has already been fixed when Julia v1.0 came out. Which version of JuliaCall are you using?

**Comment by JasperHG90** [comment]
Thanks for your response. After your comment I installed the GH version and the problem appears to be solved.

Earlier, I was running the CRAN the JuliaCall package installed from CRAN, so that version might include the conflict you mentioned.

Best,

Jasper.

**Comment by JasperHG90** [comment]
Wanted to add an additional comment to this thread to add some additional information I recently found out.

I'm using Microsoft R open. They use fixed CRAN (=MRAN) mirrors that *don't* update frequently. Hence, I was using an old package because of this and that's why the error occurred.
