### ISSUE TITLE
[JOSS] Contribution guidelines

### ISSUE THREAD

**Issue by matbesancon** [Non-Contradiction/JuliaCall#89]
The README indicates how to get help and file issue, but not guidelines for people who want to contribute (how can people help, are there some coding guidelines, should each PR correspond to at least one issue, etc)

**Comment by Non-Contradiction** [comment]
Thanks! I added a code of conduct and contributing guide following and adapted from ropensci's advice at <https://ropensci.github.io/dev_guide/collaboration.html#friendlyfiles>

**Comment by matbesancon** [comment]
Great!

**Comment by leouieda** [comment]
Linking to openjournals/joss-reviews#1284
