### ISSUE TITLE
Documenting difference between `julia_call`, `julia_eval`, `julia_command`

### ISSUE THREAD

**Issue by aguang** [Non-Contradiction/JuliaCall#92]
Would you be able to document somewhere the difference between `julia_call`, `julia_eval`, and `julia_command`? In particular the difference between these functions in returning a value to R and  returning a value to Julia.

It took me a while to understand that `julia_command` does not return a value to R, but will display return values from Julia (if `show_value=TRUE`) while `julia_eval` will not display return values from Julia but will return a value to R (if `need_return %in% c("R","Julia")`) while `julia_call` can do either/both.

**Comment by aguang** [comment]
Linking to openjournals/joss-reviews#1284

**Comment by Non-Contradiction** [comment]
The difference is already documented. However, when I look at it again, the wording is not that clear. And other users have also asked me questions about these functions. So I think I need to improve the documentation and make it more clear. Thanks for the suggestion.

**Comment by Non-Contradiction** [comment]
Documentation about these functions has been improved, and it can be retrieved by `?julia_eval` and `?julia_command`.

**Comment by aguang** [comment]
Looks good to me. Thanks!
