### ISSUE TITLE
Benchmark code

### ISSUE THREAD

**Issue by matbesancon** [Non-Contradiction/JuliaCall#94]
I couldn't find were the code for reproducing the benchmark is, it is a requirement for the JOSS submission when comparing different pieces of software or making general performance claims

**Comment by Non-Contradiction** [comment]
Thanks for taking time for the review!
The code for the benchmark result included in the paper is just located in the same folder with the paper.  See <https://github.com/Non-Contradiction/JuliaCall/blob/master/paper/XRJulia%20vs%20JuliaCall.R>
There are some comments in the script for installation of needed packages.

**Comment by matbesancon** [comment]
Thanks for your answer, it was just under my nose indeed! I would suggest mentioning the benchmark place in the paper itself, and on the README in the "alternative packages" section

**Comment by Non-Contradiction** [comment]
Thanks for the suggestion. I add a sentence in the paper for the position of the benchmark code. And I will add a link to the paper in the "alternative packages" section of README once it is accepted, so users can check the paper for a more thorough discussion on other interfaces between R and Julia.

**Comment by matbesancon** [comment]
great thank you!
